# Configuration file for the Sphinx documentation builder.
#
# Python API docs are generated by sphinx-autodoc2 using static analysis.
# The generated MyST markdown files are copied to Starlight content during CD.

# -- Project information -----------------------------------------------------
project = "Agentic Dev Library"
copyright = "2025, Jon Bogaty"
author = "Jon Bogaty"

try:
    import tomllib

    with open("../../pyproject.toml", "rb") as f:
        data = tomllib.load(f)
        release = data.get("project", {}).get("version", "0.0.0")
except Exception:
    release = "0.0.0"

# -- General configuration ---------------------------------------------------

extensions = [
    "autodoc2",
    "sphinx.ext.napoleon",
    "sphinx.ext.intersphinx",
    "myst_parser",
    "sphinx_markdown_builder",
]

templates_path = ["_templates"]
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    # Exclude non-API docs — they already live in Starlight
    "DESIGN-SYSTEM.md",
    "DOMAIN-STANDARD.md",
    "ECOSYSTEM.md",
    "getting-started/*",
    "development/*",
    "examples/*",
    "guides/*",
    "architecture/*",
    "contributing.md",
]

source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# -- Options for HTML output -------------------------------------------------

html_theme = "sphinx_rtd_theme"
html_static_path = ["_static"]
html_title = f"{project} Documentation"

# -- autodoc2 configuration (static analysis, no imports needed) -------------

autodoc2_packages = [
    {
        "path": "../../packages/agentic-crew/src/agentic_crew",
        "module": "agentic_crew",
    },
]

# Render as MyST markdown — generates .md files natively
autodoc2_render_plugin = "myst"

# Output into apidocs/ within the Sphinx source tree
autodoc2_output_dir = "apidocs"

# Parse all docstrings as MyST markdown
autodoc2_docstring_parser_regexes = [
    (r".*", "myst"),
]

# -- Napoleon configuration (Google/NumPy docstrings) -----------------------

napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = True
napoleon_use_param = True
napoleon_use_rtype = True

# -- Intersphinx configuration -----------------------------------------------

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
}

# -- MyST configuration ------------------------------------------------------

myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "fieldlist",
    "tasklist",
]
myst_heading_anchors = 3
